### ISSUE TITLE
Async or not async? That is the question

### ISSUE THREAD

**Issue by Kaspiman** [VantaFinance/temporal-bundle#3]
Hello! 

Developing an activity is easy - execution can be synchronous.

I'm trying to figure out how to build a complex workflow. As i see in [temporal.io sdk/php](https://github.com/temporalio/samples-php/blob/master/app/src/BookingSaga/TripBookingWorkflow.php) I have to use generators and yielding results. 

Do i need to use async PHP like ReactPHP for workflow execution? What will happen if the workflow launch environment is synchronous? Will there be a running process for each running workflow instance?

**Comment by root-aza** [comment]
en: 
The workflow contains only asynchronous code, since it coordinates the process. The activity may contain a synchronous code. Each activity is executed in a worker.


ru: 
В worfklow  только асинхронный код, так он координирует процесс. Activity может быть сихронным и будет выполняется на каком-то из воркеров.
